title: Digital Publishing with Scalar
remote_theme: ubc-library-rc/rc-workshop-template
search_enabled: false
github_repo_url: "https://github.com/ubc-library-rc/intro-scalar/"

# license information for workshop content
license_name: "Attribution-NonCommercial-ShareAlike 4.0 International"
license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
license_image_url: "https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
